// examples/with-vue/src/App.vue
<template>
  <button
    @click="enabled = !enabled"
    :style="{ position: 'absolute', zIndex: 1 }"
  >
    {{ enabled ? 'Enabled' : 'Disabled' }}
  </button>
  <Fireworks
    v-if="enabled"
    :options="options"
    :style="{
      top: 0,
      left: 0,
      width: '100%',
      height: '100%',
      position: 'fixed',
      background: '#000'
    }"
  />
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import { Fireworks } from '@fireworks-js/vue'
import type { FireworksOptions } from '@fireworks-js/vue'

const options = ref<FireworksOptions>({ opacity: 0.5 })
const enabled = ref(true)
</script>

// examples/with-svelte/src/App.svelte
<script lang="ts">
  import { Fireworks } from '@fireworks-js/svelte'
  import type { FireworksOptions } from '@fireworks-js/svelte'

  let enabled = true
  let options: FireworksOptions = {
    opacity: 0.5
  }
</script>

<main>
  <button on:click={() => (enabled = !enabled)} class="btn">
    {enabled ? 'Enabled' : 'Disabled'}
  </button>
  {#if enabled}
    <Fireworks {options} class="fireworks" />
  {/if}
</main>

<style>
  :global(.fireworks) {
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    position: fixed;
    background: #000;
  }

  .btn {
    position: absolute;
    z-index: 1;
  }
</style>
