// packages/vue/src/fireworks.vue
<template>
  <div ref="container"></div>
</template>

<script lang="ts" setup>
import { Fireworks } from 'fireworks-js'
import type { FireworksOptions } from 'fireworks-js'
import { PropType, onMounted, onUnmounted, ref } from 'vue'

const props = defineProps({
  options: {
    type: Object as PropType<FireworksOptions>,
    required: false
  }
})

const fireworks = ref<Fireworks>()
const container = ref<HTMLDivElement>()

onMounted(() => {
  fireworks.value = new Fireworks(container.value!, props.options)
  fireworks.value.start()
})

onUnmounted(() => {
  fireworks.value!.stop()
})
</script>

// packages/svelte/src/lib/fireworks.svelte
<div bind:this={container}></div>

<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import { Fireworks } from 'fireworks-js'
  import type { FireworksOptions } from 'fireworks-js'

  export let options: FireworksOptions
  let container: HTMLDivElement
  let fireworks: Fireworks

  onMount(() => {
    fireworks = new Fireworks(container, options)
    fireworks.start()
  })

  onDestroy(() => {
    fireworks.stop()
  })
</script>
